### ISSUE TITLE
Setting angle_start is not working as expected

### ISSUE THREAD

**Issue by SomaGallai** [SICKAG/sick_safetyscanners2#2]
I am trying to set a smaller angle for the NanoScan3, changing the values of angle_start and angle_end to 2.0 would be perfect. Changing the values of the variables in the launch file makes angle_end work as expected and changes to 2.0, but angle start set to anything lower than -1.585341453552246 is not changing to the value, it is stuck at this value.

Output of `ros2 topic echo /scan` :
```
header:
  stamp:
    sec: 1610446957
    nanosec: 159630037
  frame_id: scan
angle_min: -1.585341453552246
angle_max: 2.0187900066375732
angle_increment: 0.0029088794253766537
time_increment: 1.4000000192027073e-05
scan_time: 0.029999999329447746
range_min: 0.10000000149011612
range_max: 40.0
```
